ZenGin Archive
ver 1
zCArchiverGeneric
ASCII
saveGame 0
date 9.5.2020 14:59:14
user 42
END
objects 10       
END

[% zCMaterial 39939 0]
	name=string:NW_ADDON_SWAMPWATER_01_S05
	matGroup=enum:5
	color=color:33 49 40 180
	smoothAngle=float:60
	texture=string:NW_MISC_SWAMPWATER_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:1
	texAniMapDir=string:0 4.9999999e-005
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:0.5
	forceOccluder=bool:0
	environmentalMapping=bool:1
	environmentalMappingStrength=float:0.200000003
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:2
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 1]
	name=string:NW_ADDON_SWAMPWATER_01_S10
	matGroup=enum:5
	color=color:33 49 40 180
	smoothAngle=float:60
	texture=string:NW_MISC_SWAMPWATER_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:1
	texAniMapDir=string:0 9.9999997e-005
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:0.5
	forceOccluder=bool:0
	environmentalMapping=bool:1
	environmentalMappingStrength=float:0.200000003
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:2
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 2]
	name=string:NW_ADDON_SWAMPWATER_01_S15
	matGroup=enum:5
	color=color:33 49 40 180
	smoothAngle=float:60
	texture=string:NW_MISC_SWAMPWATER_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:1
	texAniMapDir=string:0 0.00015000001
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:0.5
	forceOccluder=bool:0
	environmentalMapping=bool:1
	environmentalMappingStrength=float:0.200000003
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:2
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 3]
	name=string:NW_ADDON_SWAMPWATER_01_S20
	matGroup=enum:5
	color=color:33 49 40 180
	smoothAngle=float:60
	texture=string:NW_MISC_SWAMPWATER_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:1
	texAniMapDir=string:0 0.00019999999
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:0.5
	forceOccluder=bool:0
	environmentalMapping=bool:1
	environmentalMappingStrength=float:0.200000003
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:2
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 4]
	name=string:NW_ADDON_SWAMPWATER_01_S25
	matGroup=enum:5
	color=color:33 49 40 180
	smoothAngle=float:60
	texture=string:NW_MISC_SWAMPWATER_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:1
	texAniMapDir=string:0 0.00025000001
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:0.5
	forceOccluder=bool:0
	environmentalMapping=bool:1
	environmentalMappingStrength=float:0.200000003
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:2
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 5]
	name=string:NW_ADDON_SWAMPWATER_01_S30
	matGroup=enum:5
	color=color:33 49 40 180
	smoothAngle=float:60
	texture=string:NW_MISC_SWAMPWATER_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:1
	texAniMapDir=string:0 0.00030000001
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:0.5
	forceOccluder=bool:0
	environmentalMapping=bool:1
	environmentalMappingStrength=float:0.200000003
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:2
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 6]
	name=string:OWODWFALL_A0_S40
	matGroup=enum:5
	color=color:120 135 134 200
	smoothAngle=float:60
	texture=string:OWODWFALL_A0.TGA
	texScale=string:512 512
	texAniFPS=float:8
	texAniMapMode=enum:1
	texAniMapDir=string:0 -0.00039999999
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:OWODWFALL_A0.TGA
	detailObjectScale=float:0.300000012
	forceOccluder=bool:0
	environmentalMapping=bool:1
	environmentalMappingStrength=float:0.400000006
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:2
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 7]
	name=string:OWODWFALL_A0_S50
	matGroup=enum:5
	color=color:120 135 134 200
	smoothAngle=float:60
	texture=string:OWODWFALL_A0.TGA
	texScale=string:512 512
	texAniFPS=float:8
	texAniMapMode=enum:1
	texAniMapDir=string:0 -0.00050000002
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:OWODWFALL_A0.TGA
	detailObjectScale=float:0.300000012
	forceOccluder=bool:0
	environmentalMapping=bool:1
	environmentalMappingStrength=float:0.400000006
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:2
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 8]
	name=string:OWODWFALL_A0_S60
	matGroup=enum:5
	color=color:120 135 134 200
	smoothAngle=float:60
	texture=string:OWODWFALL_A0.TGA
	texScale=string:512 512
	texAniFPS=float:8
	texAniMapMode=enum:1
	texAniMapDir=string:0 -0.00060000003
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:OWODWFALL_A0.TGA
	detailObjectScale=float:0.300000012
	forceOccluder=bool:0
	environmentalMapping=bool:1
	environmentalMappingStrength=float:0.400000006
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:2
	defaultMapping=rawFloat:2.34375 2.34375 
[]
[% zCMaterial 39939 9]
	name=string:NW_ADDON_SWAMPWATER_01_S00
	matGroup=enum:5
	color=color:33 49 40 180
	smoothAngle=float:60
	texture=string:NW_MISC_SWAMPWATER_01.TGA
	texScale=string:512 512
	texAniFPS=float:0
	texAniMapMode=enum:0
	texAniMapDir=string:0 0
	noCollDet=bool:0
	noLightmap=bool:0
	lodDontCollapse=bool:0
	detailObject=string:
	detailObjectScale=float:0.5
	forceOccluder=bool:0
	environmentalMapping=bool:1
	environmentalMappingStrength=float:0.200000003
	waveMode=enum:0
	waveSpeed=enum:2
	waveMaxAmplitude=float:30
	waveGridSize=float:100
	ignoreSunLight=bool:0
	alphaFunc=enum:2
	defaultMapping=rawFloat:2.34375 2.34375 
[]
